### ISSUE TITLE
你好，调用odConv在windows系统能运行，但是在linux的ubuntu出现如下错误，还麻烦再次解答一下

### ISSUE THREAD

**Issue by Wisdom2wisdom** [OSVAI/ODConv#12]
![image](https://user-images.githubusercontent.com/91510018/193041511-6b653ca8-019a-4449-9c10-065d625ea4d4.png)

然后我还没有找到解决问题的办法

**Comment by chaoli-ai** [comment]
请确保所有模型与数据统一加载在GPU或CPU上。
