### ISSUE TITLE
调用summary是报错，是什么原因呢？

### ISSUE THREAD

**Issue by peteli25** [OSVAI/ODConv#13]
![image](https://user-images.githubusercontent.com/58366052/193804320-6f1230aa-ecf5-497b-9709-d571520720ca.png)

**Comment by chaoli-ai** [comment]
https://github.com/OSVAI/ODConv/blob/60a469197241dbfa2d795145102abe0dc2750d83/modules/odconv.py#L56-L58
https://github.com/OSVAI/ODConv/blob/60a469197241dbfa2d795145102abe0dc2750d83/modules/odconv.py#L78-L83
该错误与ODConv2d的Attention实现方式有关，在kernel size为1/kernel number为1/depth-wise卷积等不同情况下，channel/filter/spatial/kernel attention中的某些attention机制将不被应用（例如ODConv不会对1×1卷积层使用spatial attention），我们的代码实现中会将相应的attention置为浮点数1.0。 针对此问题，可以先判断查看size的对象是否为tensor类型。

**Comment by yanglcs** [comment]
你好，我也遇到了同样的问题，查看size的对象是LongTensor类型，不知道要怎么解决T_T
