### ISSUE TITLE
After using this convolution to replace the backbone network convolution, the parameter quantity decreases??

### ISSUE THREAD

**Issue by yjqy12138** [OSVAI/ODConv#18]
After using this convolution to replace the backbone network convolution, the parameter quantity decreases??

**Comment by chaoli-ai** [comment]
Replacing vanilla convolution with ODConv will introduce more parameters due to the attention module. Please check your code carefully.

**Comment by yjqy12138** [comment]
I replaced the convolution in the official code of yolox, and found that the parameter quantity actually decreased
