### ISSUE TITLE
Torchsummary报错，查看类型后不知如何修改，烦请解答！

### ISSUE THREAD

**Issue by yanglcs** [OSVAI/ODConv#20]
summary[m_key]['output_shape'] = [[-1] + list(o.size())[1:] for o in output]

AttributeError: 'float' object has no attribute 'size'

![1](https://user-images.githubusercontent.com/87051085/200321896-9a60cecd-d1d8-4bf9-afe5-78cdbfa80004.png)

查看了size的对象是LongTensor类型，但不知道如何修改。请问如何解决这个问题，谢谢！

**Comment by yanglcs** [comment]
上述问题已解决，但使用odconv替换网络原有的卷积后，再训练时loss不收敛，调整lr也没有改善，是调用方式的问题，还是需要再增加新的损失函数呢？

**Comment by YaoAnbang** [comment]
odconv本身没有额外的损失函数。请先仔细参考我们code中的例子，再结合你自己的任务使用odconv，谢谢！

**Comment by FearlessArmy** [comment]
@yanglcs 怎么解决这个问题的，我这也出现这个问题
