### ISSUE TITLE
kernel_num = 4 报错输入尺寸不匹配

### ISSUE THREAD

**Issue by aaa25** [OSVAI/ODConv#24]
定义输入通道128，输出通道128，kernelsize=1，stride=1，padding=0，dilation=1，groups=1.
当kernel_num为1时模型可以正常训练，kernel_num=4时报错：
```
    output = output.view(batch_size, self.out_planes, output.size(-2), output.size(-1))
RuntimeError: shape '[16, 128, 160, 160]' is invalid for input of size 3276800
```
进入调试模式可以看到输入数据x的shape为[16,128,160,160]，经过reshape后为[1,2048,160,160],
self.weight的尺寸为[4, 128, 128, 1, 1]

aggregate_weight的尺寸为[128, 128, 1, 1]

经过F.conv2d后output的尺寸为[1, 128, 160, 160]

与下一步的output.view(batch_size, self.out_planes, output.size(-2), output.size(-1))所需的输入尺寸不符合
请问是哪里有问题呢？

**Comment by chaoli-ai** [comment]
看起来aggregate_weight的尺寸并不对，对于batch size=1的输入，应该是[16 * 128, 128, 1, 1]才对。
可以去查看下您kernel_attention的shape，如果kernel_attention是标量1而非形如[16,4,1,1,1,1]的tensor的话，说明Attention内的self.func_kernel被设置成了self.skip，可能是Attention对应的kernel_num输入为了1而非4.
