### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by wafaer** [OSVAI/ODConv#26]
Hello, I would like to ask you a question. When I am training, I get this error: TypeError: __init__() got an unexpected keyword argument 'reduction'
. I can't think of a solution, do you have any insight?

**Comment by chaoli-ai** [comment]
For networks applied with ODConv, we add two extra arguments "reduction" and "kernel_num". If you want to apply ODConv to other networks or use our code to train other networks, please remember to add the two input arguments to your network and its modules.

**Comment by 18109359681** [comment]
> 对于使用 ODConv 应用的网络，我们添加了两个额外的参数“reduction”和“kernel_num”。如果您想将 ODConv 应用于其他网络或使用我们的代码来训练其他网络，请记住将两个输入参数添加到您的网络及其模块中。
你好，我也遇到了这个问题，请问可以说的详细一点吗，我替换了resnet中的卷积

**Comment by 18109359681** [comment]
> 您好，我想问您一个问题。当我训练时，我收到此错误： TypeError： **init**（） got an unexpected keyword argument 'reduction' 。我想不出解决方案，你有什么见解吗？

你好，我也是这个问题，解决了嘛
