### ISSUE TITLE
I replaced the individual conv in yolo with odconv and the following error occurred

### ISSUE THREAD

**Issue by trytry1206** [OSVAI/ODConv#27]
![image](https://user-images.githubusercontent.com/126448039/221495657-d8da6990-da71-4cdb-8075-edf86c24c600.png)
I replaced the individual conv in yolo with odconv and the following error occurred
![image](https://user-images.githubusercontent.com/126448039/221495957-22bd3fac-9a03-459b-9e4a-b0ed644aed88.png)

**Comment by trytry1206** [comment]
而且我yolo中设置的batch size并不是1

**Comment by ZVChen** [comment]
yolo在开始训练前会尝试输入一个随机张量来测试模型，可以通过判断来跳过BN层。批量为1的情况下，BN层实际上是不起作用的

**Comment by CVwbp** [comment]
> yolo在开始训练前会尝试输入一个随机张量来测试模型，可以通过判断来跳过BN层。批量为1的情况下，BN层实际上是不起作用的

请问您有没有试过加载作者提出的预训练权重呢？

**Comment by ZVChen** [comment]
> > yolo在开始训练前会尝试输入一个随机张量来测试模型，可以通过判断来跳过BN层。批量为1的情况下，BN层实际上是不起作用的
> 
> 请问您有没有试过加载作者提出的预训练权重呢？

没有使用这个预训练权重，只是尝试替换了yolo中的卷积

**Comment by trytry1206** [comment]
> yolo在开始训练前会尝试输入一个随机张量来测试模型，可以通过判断来跳过BN层。批量为1的情况下，BN层实际上是不起作用的

感谢 我之前是删去了foward里面的BN层 可以正常运行 我现在试试通过判断来跳过BN层
