### ISSUE TITLE
After replace Conv2d to ODConv2d, how to fused conv and bn?

### ISSUE THREAD

**Issue by nikbobo** [OSVAI/ODConv#30]
My net is like conv-bn-relu。
I replaced nn.conv2d to odconv2d, and wanted to fused conv and batchnorm in inference.

我替换成了 ODConv 以后如何像之前那样在推理阶段融合 Conv 和 BN 层？在 Conv-BN-ReLU/SiLU/GELU 这样结构的 CNN 网络中？

**Comment by YaoAnbang** [comment]
You may first combine static conv kernel and BN, then apply dynamic attentions leant by ODConv.
