### ISSUE TITLE
I would like to ask how to use the model

### ISSUE THREAD

**Issue by shadollFusion** [OSVAI/ODConv#32]
I downloaded the model and got an 'archive' folder.When I try to load it with torch.load, I get an error '**_pickle.UnpicklingError: A load persistent id instruction was encountered,but no persistent_load function was specified.‘**
but no persistent_load function was specified.’, but I want to have a backbone pre-trained model (the best .pth file) to complete my other tasks, what should I do

**Comment by YaoAnbang** [comment]
I believe you can solve it by yourself.
