### ISSUE TITLE
你好，请问复现自己的数据集格式，该怎么制作

### ISSUE THREAD

**Issue by Wisdom2wisdom** [OSVAI/ODConv#6]
谢谢

**Comment by chaoli-ai** [comment]
如果希望更换使用其他数据集，需要修改的地方有以下三处
（1）根据所使用的数据集修改normalize的均值与标准差
https://github.com/OSVAI/ODConv/blob/60a469197241dbfa2d795145102abe0dc2750d83/main.py#L169-L173
（2）根据需要修改训练集的预处理流程
https://github.com/OSVAI/ODConv/blob/60a469197241dbfa2d795145102abe0dc2750d83/main.py#L175-L182
（3）根据需要修改测试集的预处理流程
https://github.com/OSVAI/ODConv/blob/60a469197241dbfa2d795145102abe0dc2750d83/main.py#L191-L198

数据集的准备方式可以参考https://pytorch.org/vision/stable/generated/torchvision.datasets.ImageFolder.html#torchvision.datasets.ImageFolder
（1）创建一总文件夹，对应代码中的args.data
（2）在总文件夹下创建名为train与val的两个文件夹，分别代表训练集与测试集
（3）在train与val文件夹下为每个类别分别创建一子文件夹
（4）将每个类别的图像数据存储进对应的子文件夹内
（5）更改训练时所输入的  --data {path to dataset}  为上述总文件夹路径

**Comment by Wisdom2wisdom** [comment]
你好，已经弄好了部分数据集，可是训练时候出现如下问题，一直没有找到方法解决

![image](https://user-images.githubusercontent.com/91510018/192194918-5ea11a45-b99c-4a60-aef5-b70469ad600a.png)


请问该问题该如何解决啊，谢谢
