### ISSUE TITLE
about odc onvolution kernel_size

### ISSUE THREAD

**Issue by vaerdu** [OSVAI/ODConv#7]
odc模块里的kernel_size可以是1*1大小的吗？

**Comment by vaerdu** [comment]
odc模块里的kernel_size可以是1*1大小的吗？

**Comment by chaoli-ai** [comment]
是可以的。当kernel size设置为1时，ODConv会去除掉spatial attention，因为我们认为对大小为1×1的卷积核作空间尺度上的attention没有意义。

https://github.com/OSVAI/ODConv/blob/60a469197241dbfa2d795145102abe0dc2750d83/modules/odconv.py#L29-L33
